### ISSUE TITLE
Missing content about hack/hjack to server, rules documentation doesn't professional enough.

### ISSUE THREAD

**Issue by FLYEMOJ1** [vdriasworld/manual#10]
Same as title

**Comment by FLYEMOJ1** [comment]
This still needs to do.

Fix in progress.

烦请各位 Contributer 在时间足够时提供相关协助。
@Mashirl @Lemon-miaow @gxres042

**Comment by Mashirl** [comment]
I think so, that's a problem. I wanna fix them but I can't have a point about that. Do you have some ideas?

**Comment by Mashirl** [comment]
@FLYEMOJ1

**Comment by FLYEMOJ1** [comment]
> I think so, that's a problem. I wanna fix them but I can't have a point about that. Do you have some ideas?

说中文我操
这个今天解决不了 我现在在外面 等有时间我发pr

**Comment by Mashirl** [comment]
> > I think so, that's a problem. I wanna fix them but I can't have a point about that. Do you have some ideas?
> 
> 说中文我操 这个今天解决不了 我现在在外面 等有时间我发pr

了解，感谢

**Comment by Lemon-miaow** [comment]
蒋英文

**Comment by FLYEMOJ1** [comment]
> 蒋英文

自己滚出去

**Comment by FLYEMOJ1** [comment]
哈哈 傻逼了 直接推上去了 你们看看这个版本的 rules.md 有问题就直接在这个 Issue 下面 comment

**Comment by Mashirl** [comment]
#11 @FLYEMOJ1 @Lemon-miaow
