### ISSUE TITLE
markdown 文档格式问题

### ISSUE THREAD

**Issue by Michael18811380328** [vdriasworld/manual#4]
上传的文档中 markdown 格式不正确，例如
::: warning
使用第三方软件出现的任何问题，Vdrias World! 不负任何责任。
:::
这里需要表达什么意思呢？我可以批量帮助修改
另外，我也是MC入门玩家，期待加入。

**Comment by jinzhijie** [comment]
这是 Vuepress 提供的语法，非原版 Markdown 所有。你可以前往 https://manual.vdrias.cn 查看编译后的格式。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月22日(星期一) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[vdriasworld/manual] markdown 文档格式问题 (#4)

**Comment by Michael18811380328** [comment]
好的，原来是 vuePress 的格式，学到了
